from __future__ import annotations

import hashlib
import json
import os
import shutil
import zipfile
from abc import abstractmethod
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Literal
from urllib.parse import quote, urljoin, urlsplit

from simulac.base.envvar.envvar import IEnvvarService
from simulac.base.error.error import SimulacBaseError
from simulac.base.instantiate.instantiate import ServiceIdentifier, service_identifier
from simulac.sdk.file_service.common.files import IFileService
from simulac.sdk.log_service.common.log_service import ILogService
from simulac.sdk.telemetry_service.common.telemetry_service import ITelemetryService

if TYPE_CHECKING:
    from simulac.sdk.environment_service.common.environment import (
        EnvironmentMachineEntity,
        EnvironmentStuffEntity,
        IEnvironment,
    )

"""
TODO: @gangjeuk
[ ] - clean code
        - Backend API spec is not finalized yet
[ ] - need asset curation
        - There are some assets don't follow our standard format

"""


@dataclass(frozen=True)
class ResolvedAsset:
    """Baseically http response type from backend '/api/asset/' route"""

    asset_ref: str
    asset_id: str
    format: str
    entrypoint: Path
    cache_dir: Path


@service_identifier("IAssetService")
class IAssetService(ServiceIdentifier["IAssetService"]):
    @abstractmethod
    def resolve_obj_bundle(self, source_uri: str): ...

    @abstractmethod
    def resolve_mjcf_bundle(self, source_uri: str): ...

    @abstractmethod
    def resolve_bundle(self, source_uri: str): ...

    @abstractmethod
    def resolve_remote_bundle(self, source_uri: str): ...

    @abstractmethod
    def resolve_environment_assets(self, env: IEnvironment) -> None: ...

    @abstractmethod
    def resolve_asset(
        self, asset_ref: str, *, format: str = "mjcf"
    ) -> ResolvedAsset: ...


class AssetService(IAssetService):
    def __init__(
        self,
        EnvvarService: IEnvvarService,
        FileService: IFileService,
        LogService: ILogService,
        TelemetryService: ITelemetryService,
    ) -> None:
        self.EnvvarService = EnvvarService
        self.FileService = FileService
        self.LogService = LogService
        self.TelemetryService = TelemetryService

    def resolve_environment_assets(self, env: IEnvironment) -> None:

        asset_groups: dict[
            str, list[EnvironmentMachineEntity | EnvironmentStuffEntity]
        ] = defaultdict(list)
        # filtering duplicate asset
        for entity in [*env.stuffs, *env.machines]:
            if not entity.asset_uri:
                continue

            if entity.original_asset_uri is None:
                entity.original_asset_uri = entity.asset_uri

            if self._is_builtin_primitive_ref(entity.asset_uri):
                continue

            ref_kind = self._classify_asset_ref(entity.asset_uri)
            if ref_kind == "local_file":
                local = self._local_path(entity.asset_uri)
                key = str(
                    local.resolve() if local else Path(entity.asset_uri).resolve()
                )
            else:
                key = self._canonical_asset_id(entity.asset_uri)

            asset_groups[key].append(entity)

        groups = list(asset_groups.values())
        if not groups:
            return
        # parallel download
        max_workers = min(len(groups), (os.cpu_count() or 4))

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(
                    self.resolve_asset, group[0].asset_uri, format="mjcf"
                ): group
                for group in groups
            }
            for idx, future in enumerate(as_completed(futures), start=1):
                resolved = future.result()
                group = futures[future]

                for entity in group:
                    entity.asset_uri = str(resolved.entrypoint)

                self.LogService.info(
                    f"Asset resolved ({idx}/{len(groups)}): {resolved.asset_id}"
                )

    def resolve_asset(self, asset_ref: str, *, format: str = "mjcf") -> ResolvedAsset:
        if self._is_builtin_primitive_ref(asset_ref):
            raise SimulacBaseError(
                f"Built-in primitive {asset_ref!r} is generated by the physics adapter."
            )

        ref_kind = self._classify_asset_ref(asset_ref)

        if ref_kind == "local_file":
            local = self._local_path(asset_ref)
            if local is None or not local.exists():
                raise SimulacBaseError(f"Local asset file does not exist: {asset_ref}")

            return ResolvedAsset(
                asset_ref=asset_ref,
                asset_id=str(local),
                format=format,
                entrypoint=local,
                cache_dir=local.parent,
            )

        if ref_kind == "direct_url":
            raise SimulacBaseError(
                "Direct asset URLs are not supported. "
                "Use a Tektonian asset id like 'Robocasa/tray/aigen_objs_tray_4'."
                "Visit https://tektonian.com/asset page to see available asset list"
            )

        asset_id = self._canonical_asset_id(asset_ref)
        cache_dir = self.EnvvarService.asset_dir / self._safe_asset_id(asset_id)
        zip_path = cache_dir / f"{format}.zip"
        files_dir = cache_dir / format
        tmp_dir = cache_dir / ".tmp"
        verified_path = cache_dir / ".verified.json"

        cached_meta = self._load_verified_cache_metadata(verified_path)
        if cached_meta is not None:
            cached_entrypoint = files_dir / cached_meta["entrypoint"]
            if self._valid_extracted_cache(files_dir, cached_entrypoint, verified_path):
                return ResolvedAsset(
                    asset_ref=asset_ref,
                    asset_id=cached_meta["asset_id"],
                    format=cached_meta.get("format", format),
                    entrypoint=cached_entrypoint,
                    cache_dir=cache_dir,
                )

        meta = self._fetch_manifest(asset_id, format=format)
        entrypoint = files_dir / meta["entrypoint"]

        if self._valid_extracted_cache(files_dir, entrypoint, verified_path):
            return ResolvedAsset(
                asset_ref=asset_ref,
                asset_id=meta["asset_id"],
                format=format,
                entrypoint=entrypoint,
                cache_dir=cache_dir,
            )

        cache_dir.mkdir(parents=True, exist_ok=True)
        if tmp_dir.exists():
            shutil.rmtree(tmp_dir)
        tmp_files_dir = tmp_dir / format
        tmp_files_dir.mkdir(parents=True, exist_ok=True)

        download_url = self._absolute_backend_url(meta["download_url"])
        data, err = self.FileService.read_file(urlsplit(download_url))
        if err:
            raise err

        _, err = self.FileService.create_file(
            urlsplit(zip_path.as_uri()),
            data,
            overwrite=True,
        )
        if err:
            raise err

        self._safe_unzip(zip_path, tmp_files_dir)
        extracted_files_dir = self._extracted_asset_root(tmp_files_dir, format)
        self._verify_extracted_asset(extracted_files_dir)

        tmp_entrypoint = extracted_files_dir / meta["entrypoint"]
        if not tmp_entrypoint.exists():
            raise SimulacBaseError(
                f"Asset entrypoint does not exist after unzip: {tmp_entrypoint}"
            )

        if files_dir.exists():
            shutil.rmtree(files_dir)
        extracted_files_dir.rename(files_dir)
        shutil.rmtree(tmp_dir, ignore_errors=True)

        verified_path.write_text(
            json.dumps(
                {
                    "asset_id": meta["asset_id"],
                    "format": format,
                    "entrypoint": meta["entrypoint"],
                    "download_url": meta["download_url"],
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

        return ResolvedAsset(
            asset_ref=asset_ref,
            asset_id=meta["asset_id"],
            format=format,
            entrypoint=entrypoint,
            cache_dir=cache_dir,
        )

    def _load_verified_cache_metadata(
        self,
        verified_path: Path,
    ) -> dict[str, str] | None:
        if not verified_path.exists():
            return None

        try:
            metadata = json.loads(verified_path.read_text(encoding="utf-8"))
        except Exception:
            return None

        if not isinstance(metadata, dict):
            return None
        if "asset_id" not in metadata or "entrypoint" not in metadata:
            return None

        return {
            "asset_id": str(metadata["asset_id"]),
            "format": str(metadata.get("format", "")),
            "entrypoint": str(metadata["entrypoint"]),
            "download_url": str(metadata.get("download_url", "")),
        }

    def _fetch_manifest(self, asset_id: str, *, format: str) -> dict[str, str]:
        token = self.EnvvarService.token

        data, err = self.FileService.read_file(
            urlsplit(self._manifest_url(asset_id, format=format, token=token))
        )
        if err and token:
            data, err = self.FileService.read_file(
                urlsplit(self._manifest_url(asset_id, format=format, token=None))
            )
        if err:
            raise err

        manifest = json.loads(data.decode("utf-8"))
        return {
            "asset_id": manifest["asset_id"],
            "format": manifest.get("format", format),
            "download_url": manifest["download_url"],
            "entrypoint": manifest.get("entrypoint", "model.xml"),
        }

    def _manifest_url(self, asset_id: str, *, format: str, token: str | None) -> str:
        return (
            f"{self.EnvvarService.base_url.rstrip('/')}"
            f"/asset/sim-asset"
            f"?asset_id={quote(asset_id, safe='')}"
            f"&format={quote(format, safe='')}"
            f"&api_key={quote(token or '', safe='')}"
        )

    def _valid_extracted_cache(
        self,
        files_dir: Path,
        entrypoint: Path,
        verified_path: Path,
    ) -> bool:
        if (
            not files_dir.exists()
            or not entrypoint.exists()
            or not verified_path.exists()
        ):
            return False

        try:
            self._verify_extracted_asset(files_dir)
        except Exception:
            return False

        return True

    def _verify_extracted_asset(self, files_dir: Path) -> None:
        manifest_path = files_dir / "metadata" / "file_manifest.jsonl"
        if not manifest_path.exists():
            self.__warn_asset_file_manifest_missing(
                files_dir=files_dir,
                manifest_path=manifest_path,
            )
            return

        for line_number, line in enumerate(
            manifest_path.read_text(encoding="utf-8").splitlines(),
            start=1,
        ):
            if not line.strip():
                continue

            item = json.loads(line)
            manifest_file_path = item["path"]

            candidates = [files_dir / manifest_file_path]
            if manifest_file_path.startswith("files/"):
                candidates.append(files_dir / manifest_file_path.removeprefix("files/"))

            file_path = next((path for path in candidates if path.exists()), None)
            if file_path is None:
                self.__warn_asset_manifest_file_missing(
                    manifest_path=manifest_path,
                    manifest_file_path=manifest_file_path,
                    line_number=line_number,
                )
                continue

            expected_size = int(item["size_bytes"])
            actual_size = file_path.stat().st_size
            if actual_size != expected_size:
                self._warn_asset_file_size_mismatch(
                    manifest_path=manifest_path,
                    manifest_file_path=manifest_file_path,
                    file_path=file_path,
                    line_number=line_number,
                    expected_size=expected_size,
                    actual_size=actual_size,
                )
                continue

            expected_hash = item["sha256"]
            actual_hash = self._sha256(file_path)
            if actual_hash != expected_hash:
                self.__warn_asset_file_checksum_mismatch(
                    manifest_path=manifest_path,
                    manifest_file_path=manifest_file_path,
                    file_path=file_path,
                    line_number=line_number,
                    expected_hash=expected_hash,
                    actual_hash=actual_hash,
                )

    def _classify_asset_ref(
        self,
        value: str,
    ) -> Literal["local_file", "direct_url", "asset_id"]:
        if self._is_builtin_primitive_ref(value):
            return "asset_id"

        if value.startswith(("http://", "https://")):
            return "direct_url"
        if value.startswith("file://"):
            return "local_file"

        path = Path(value)
        if path.exists():
            return "local_file"

        if path.suffix.lower() in {
            ".xml",
            ".mjcf",
            ".urdf",
            ".usd",
            ".usda",
            ".usdc",
            ".obj",
            ".glb",
            ".gltf",
        }:
            raise SimulacBaseError(f"Local asset file does not exist: {value}")

        return "asset_id"

    def _is_builtin_primitive_ref(self, value: str) -> bool:
        return value.strip().lower().startswith("simulac://primitive/")

    def _local_path(self, asset_ref: str) -> Path | None:
        if asset_ref.startswith("file://"):
            return Path(urlsplit(asset_ref).path)
        if "://" in asset_ref:
            return None
        return Path(asset_ref)

    def _canonical_asset_id(self, value: str) -> str:
        return value.strip().replace("\\", "/").strip("/").lower()

    def _absolute_backend_url(self, value: str) -> str:
        if value.startswith(("http://", "https://")):
            return value
        return urljoin(
            f"{self.EnvvarService.base_url.rstrip('/')}/",
            value.lstrip("/"),
        )

    def _safe_unzip(self, zip_path: Path, target_dir: Path) -> None:
        root = target_dir.resolve()
        with zipfile.ZipFile(zip_path) as archive:
            for member in archive.infolist():
                dest = (target_dir / member.filename).resolve()
                if root not in [dest, *dest.parents]:
                    raise SimulacBaseError(f"Unsafe zip member path: {member.filename}")
            archive.extractall(target_dir)

    def _extracted_asset_root(self, files_dir: Path, format: str) -> Path:
        if (files_dir / "metadata" / "file_manifest.jsonl").exists():
            return files_dir

        format_dir = files_dir
        if (format_dir / "metadata" / "file_manifest.jsonl").exists():
            return format_dir
        for child in files_dir.iterdir():
            if child.is_file() and child.name.endswith(f".{format}"):
                return format_dir

        candidates = [
            child
            for child in files_dir.iterdir()
            if child.is_dir()
            and not child.name.startswith(".")
            and child.name != "__MACOSX"
            and (child / "metadata" / "file_manifest.jsonl").exists()
        ]
        if len(candidates) == 1:
            return candidates[0]

        model_xml_candidates = [
            child
            for child in files_dir.iterdir()
            if child.is_dir()
            and not child.name.startswith(".")
            and child.name != "__MACOSX"
            and (child / "model.xml").exists()
        ]
        if len(model_xml_candidates) == 1:
            return model_xml_candidates[0]

        return files_dir

    def _sha256(self, path: Path) -> str:
        h = hashlib.sha256()
        with path.open("rb") as file:
            for chunk in iter(lambda: file.read(1024 * 1024), b""):
                h.update(chunk)
        return h.hexdigest()

    def _safe_asset_id(self, value: str) -> str:
        return value.replace("\\", "/").strip("/").replace("..", "__")

    def _warn_asset_file_size_mismatch(
        self,
        *,
        manifest_path: Path,
        manifest_file_path: str,
        file_path: Path,
        line_number: int,
        expected_size: int,
        actual_size: int,
    ) -> None:
        self.LogService.warn(
            "Asset file size mismatch. "
            f"file={file_path}, expected={expected_size}, actual={actual_size}"
        )
        self.TelemetryService.public_error(
            "simulac_asset_file_size_mismatch",
            {
                "manifest_path": str(manifest_path),
                "manifest_line": str(line_number),
                "manifest_file_path": manifest_file_path,
                "file_path": str(file_path),
                "expected_size": str(expected_size),
                "actual_size": str(actual_size),
            },
        )

    def __warn_asset_file_manifest_missing(
        self,
        *,
        files_dir: Path,
        manifest_path: Path,
    ) -> None:
        self.LogService.warn(f"Asset file manifest is missing: {manifest_path}")
        self.TelemetryService.public_error(
            "simulac_asset_file_manifest_missing",
            {
                "files_dir": str(files_dir),
                "manifest_path": str(manifest_path),
            },
        )

    def __warn_asset_manifest_file_missing(
        self,
        *,
        manifest_path: Path,
        manifest_file_path: str,
        line_number: int,
    ) -> None:
        self.LogService.warn(
            "Asset manifest file is missing. "
            f"manifest={manifest_path}, line={line_number}, file={manifest_file_path}"
        )
        self.TelemetryService.public_error(
            "simulac_manifest_file_missing",
            {
                "manifest_path": str(manifest_path),
                "manifest_line": str(line_number),
                "manifest_file_path": manifest_file_path,
            },
        )

    def __warn_asset_file_checksum_mismatch(
        self,
        *,
        manifest_path: Path,
        manifest_file_path: str,
        file_path: Path,
        line_number: int,
        expected_hash: str,
        actual_hash: str,
    ) -> None:
        self.LogService.warn(
            "Asset file checksum mismatch. "
            f"file={file_path}, expected={expected_hash}, actual={actual_hash}"
        )
        self.TelemetryService.public_error(
            "simulac_file_checksum_mismatch",
            {
                "manifest_path": str(manifest_path),
                "manifest_line": str(line_number),
                "manifest_file_path": manifest_file_path,
                "file_path": str(file_path),
                "expected_sha256": expected_hash,
                "actual_sha256": actual_hash,
            },
        )
