from __future__ import annotations

from typing import Callable, Protocol, runtime_checkable


@runtime_checkable
class IStuffRuntimeOps(Protocol):
    def get_pos(self) -> tuple[float, float, float]: ...
    def get_quat(self) -> tuple[float, float, float, float]: ...
    def get_mass(self) -> float: ...
    def get_friction(self) -> float: ...

    def change_pos(self, pos: tuple[float, float, float]) -> None: ...
    def change_quat(self, quat: tuple[float, float, float, float]) -> None: ...
    def change_mass(self, mass: float) -> None: ...
    def change_friction(self, friction: float) -> None: ...


class StuffRuntime:
    def __init__(self, entity_id: str, ops: IStuffRuntimeOps) -> None:
        self.id = entity_id
        self._ops = ops

    def get_pos(self) -> tuple[float, float, float]:
        return self._ops.get_pos()

    def get_quat(self) -> tuple[float, float, float, float]:
        return self._ops.get_quat()

    def get_mass(self) -> float:
        return self._ops.get_mass()

    def get_friction(self) -> float:
        return self._ops.get_friction()

    def change_pos(self, pos: tuple[float, float, float]) -> None:
        self._ops.change_pos(pos)

    def change_quat(self, quat: tuple[float, float, float, float]) -> None:
        self._ops.change_quat(quat)

    def change_mass(self, mass: float) -> None:
        self._ops.change_mass(mass)

    def change_friction(self, friction: float) -> None:
        self._ops.change_friction(friction)


class IRobotRuntimeOps(Protocol):
    # below two are for mobile robot or floating boat
    def get_base_pos(self) -> tuple[float, float, float]: ...
    def get_base_quat(self) -> tuple[float, float, float]: ...

    def get_joint_pos(self) -> list[float]: ...
    def get_joint_vel(self) -> list[float]: ...

    def change_joint_pos(self, joint_pos: list[float]) -> None: ...
    def change_joint_vel(self, joint_vel: list[float]) -> None: ...

    def step(self, action: list[float]) -> None: ...
    def tick(self) -> None: ...


class RobotJointRuntime:
    def get_pos(self) -> float: ...
    def get_vel(self) -> float: ...
    def change_pos(self, pos: float) -> None: ...
    def change_vel(self, vel: float) -> None: ...

    def change_target_pos(self, pos: float) -> None: ...
    # NOTE: below two are future use,
    # since our team concluded that we are focuing on `pos` control
    def _change_target_vel(self, vel: float) -> None: ...
    def _change_target_force(self, force: float) -> None: ...


class RobotLinkRuntime:
    def get_pos(self) -> tuple[float, float, float]: ...
    def get_quat(self) -> tuple[float, float, float, float]: ...


class ICameraRuntimeOps(Protocol):
    def get_pos(self) -> tuple[float, float, float]: ...
    def get_quat(self) -> tuple[float, float, float, float]: ...

    def change_pos(self, pos: tuple[float, float, float]) -> None: ...
    def change_quat(self, quat: tuple[float, float, float, float]) -> None: ...

    def get_fov(self) -> float: ...
    def change_fov(self, fov: float) -> None: ...


class ILightRuntimeOps(Protocol):
    def get_pos(self) -> tuple[float, float, float]: ...
    def get_quat(self) -> tuple[float, float, float, float]: ...

    def change_pos(self, pos: tuple[float, float, float]) -> None: ...
    def change_quat(self, quat: tuple[float, float, float, float]) -> None: ...

    def get_color(self) -> tuple[float, float, float]: ...
    def change_color(self, color: tuple[float, float, float]) -> None: ...

    def get_intensity(self) -> float: ...
    def change_intensity(self, intensity: float) -> None: ...


class ISpotLightRuntimeOps(Protocol):
    def get_angle(self) -> float: ...
    def change_angle(self, angle: float) -> None: ...


class IAreaLightRuntimeOps(Protocol):
    def get_area_size(self) -> tuple[float, float]: ...
    def change_area_size(self, width: float, height: float) -> None: ...


class IDirectionalLightRuntimeOps(Protocol):
    def get_direction(self) -> tuple[float, float, float]: ...
    def change_direction(self, direction: tuple[float, float, float]) -> None: ...
